import type { Detection } from "../detect/types.js";
import type { DougConfig } from "./config.js";

// Generates standard project subagents under .claude/agents/: coder, architect, reviewer, researcher, and
// (when a test framework is detected) tester. Pure function of its arguments: no filesystem,
// no clock, no randomness, so the same inputs give byte-identical output.

export const AGENT_MARK = "doug: generated";

/** The old HTML-comment marker, kept only so isDougAgent still recognizes files written by the old generator. */
export const LEGACY_AGENT_MARK =
  "<!-- Generated by doug init. It refreshes this file while this line is present; remove the line to own the file. -->";

/** The heading that starts the user-owned section every generated agent file ends with. */
export const PROJECT_NOTES_HEADING = "## Project notes";

export function isDougAgent(text: string): boolean {
  if (text.includes(LEGACY_AGENT_MARK)) return true;
  const withoutBom = text.startsWith("﻿") ? text.slice(1) : text;
  const lines = withoutBom.split("\n").map((l) => (l.endsWith("\r") ? l.slice(0, -1) : l));
  if (lines[0] !== "---") return false;
  const closingIdx = lines.indexOf("---", 1);
  if (closingIdx <= 0) return false;
  return lines.slice(0, closingIdx).includes(AGENT_MARK);
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Line-anchored: matches only a line that equals PROJECT_NOTES_HEADING exactly, never a substring
// (a mid-line mention, or a "### Project notes" heading with an extra "#").
const PROJECT_NOTES_HEADING_RE = new RegExp(`^${escapeRegExp(PROJECT_NOTES_HEADING)}$`, "m");

/**
 * Returns `generated` with its (empty) `## Project notes` section replaced by the verbatim section from
 * `existing`, when `existing` has that heading (as its own line; the first such line if there is more than
 * one), else returns `generated` unchanged (an old-form file with no such section). Pure: no filesystem.
 */
export function spliceProjectNotes(generated: string, existing: string): string {
  const existingMatch = PROJECT_NOTES_HEADING_RE.exec(existing);
  if (!existingMatch) return generated;
  const genMatch = PROJECT_NOTES_HEADING_RE.exec(generated);
  if (!genMatch) return generated;
  return generated.slice(0, genMatch.index) + existing.slice(existingMatch.index);
}

export interface AgentFile {
  path: string;
  content: string;
}

interface AgentSpec {
  name: string;
  description: string;
  readOnly: boolean;
  /** The tools line for a read-only role; the default is the checkout-only set. */
  tools?: string;
  facts: string[];
  rules: string[];
}

function buildFacts(
  d: Detection,
  cfg: DougConfig,
  opts: { pm?: boolean; singleTest?: boolean; gate?: boolean; monorepo?: boolean; ci?: boolean }
): string[] {
  const n = d.node;
  const facts: string[] = [];
  if (opts.pm && n.packageManager) facts.push(`Use ${n.packageManager} only.`);
  if (opts.pm && d.python.present && d.python.manager) facts.push(`Use ${d.python.manager} only for Python.`);
  if (opts.singleTest && n.singleTestCommand) facts.push(`Run one test file with: ${n.singleTestCommand}`);
  if (opts.singleTest && d.python.present && d.python.singleTestCommand) {
    facts.push(`Run one Python test file with: ${d.python.singleTestCommand}`);
  }
  if (opts.gate && cfg.stopGate.commands.length) {
    facts.push(`Before finishing run: ${cfg.stopGate.commands.map((name) => cfg.commands[name]).join(" then ")}`);
  }
  if (opts.monorepo && n.monorepo.length) {
    facts.push(`Monorepo (${n.monorepo.map((m) => m.tool).join(",")}): run scripts from the package you are changing.`);
  }
  if (opts.ci && d.repo.ci.length) {
    facts.push(`CI: ${d.repo.ci.join(",")}. Mirror its checks locally.`);
  }
  return facts;
}

function renderAgent(spec: AgentSpec): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`name: ${spec.name}`);
  lines.push(`description: ${JSON.stringify(spec.description)}`);
  lines.push("model: inherit");
  if (spec.readOnly) {
    lines.push(`tools: ${spec.tools ?? "Read, Grep, Glob, Bash"}`);
    lines.push("disallowedTools: Edit, Write, MultiEdit, NotebookEdit");
  } else {
    lines.push("disallowedTools: Agent");
  }
  lines.push(AGENT_MARK);
  lines.push("---");
  lines.push("");
  if (spec.facts.length) {
    lines.push("## Facts");
    lines.push("");
    for (const f of spec.facts) lines.push(`- ${f}`);
    lines.push("");
  }
  lines.push("## Rules");
  lines.push("");
  for (const r of spec.rules) lines.push(`- ${r}`);
  lines.push("");
  lines.push(PROJECT_NOTES_HEADING);
  return lines.join("\n") + "\n";
}

export function generateAgents(d: Detection, cfg: DougConfig): AgentFile[] {
  const n = d.node;

  const coder: AgentSpec = {
    name: "coder",
    description: "Implements a requested change in this repository, runs its checks, and reports what it ran",
    readOnly: false,
    facts: buildFacts(d, cfg, { pm: true, singleTest: true, gate: true, monorepo: true }),
    rules: [
      "Do only what was asked, no refactors or renames beyond it.",
      "Add or update the test with the change.",
      "Never bypass hooks with --no-verify.",
      "Do not claim done until the gate passed in this session.",
      "Report every command run with its exit status.",
      "Return partial=true only after a hook tells you `[doug] Worker context at <pct>% of <window> tokens`: stop at a boundary (finish the file you are on and its named test, then commit), and say what's done, what's left, what to do next, and how to verify it. Never claim partial to dodge a hard task.",
      "When a test contradicts the brief or the card's goal, do not change production code to fit the test; stop and report the conflict, quoting both, so the lead can send it back to the tester.",
      "Apply each mutation in a scratch copy or git worktree under `.doug/.state`, run the one test file there, and remove the copy.",
      "Scratch files go under `.doug/.state/scratch`; protect-paths keeps refusing the Claude Code session scratchpad, which is outside the project.",
      "Run any command that can take over 120 s, such as pnpm test:unit, with the Bash timeout set to 600000, and hand back only after it exits.",
    ],
  };

  const architect: AgentSpec = {
    name: "architect",
    description: "Reads the code and returns a design: files to change, tests to add, and the command that verifies each; writes no code",
    readOnly: true,
    facts: buildFacts(d, cfg, { monorepo: true, singleTest: true, gate: true }),
    rules: [
      "Read before proposing.",
      "Return a numbered list of files with what changes in each.",
      "Name the test file and verify command per item.",
      "Do not edit.",
    ],
  };

  const reviewer: AgentSpec = {
    name: "reviewer",
    description: "Reviews a diff against its request, runs the project checks, and reports blocker, major, and minor findings; never edits",
    readOnly: true,
    facts: buildFacts(d, cfg, { gate: true, singleTest: true, ci: true }),
    rules: [
      "Review `git diff` (or `git diff <base>...HEAD` when a base is named).",
      "Run the gate commands and report real exit codes.",
      "When the change's point is that a mechanism exists, mutate or remove it, rerun the test, and confirm it fails before reverting.",
      "Severity blocker/major/minor with blocker meaning the change must not merge.",
      "Do not ask for work beyond the request.",
      "Apply each mutation in a scratch copy or git worktree under `.doug/.state`, run the one test file there, and remove the copy.",
      "Run any command that can take over 120 s, such as pnpm test:unit, with the Bash timeout set to 600000, and hand back only after it exits.",
    ],
  };

  const researcher: AgentSpec = {
    name: "researcher",
    description:
      "Answers one question about a fact outside this repository (a CLI's output, a third-party API, a package's constraints) from primary sources, quoting each fact's URL or command output and marking the rest unverified; never writes",
    readOnly: true,
    tools: "Read, Grep, Glob, Bash, WebFetch, WebSearch",
    facts: buildFacts(d, cfg, { pm: true }),
    rules: [
      "Answer the one question asked; leave any other researcher's question alone.",
      "Primary sources first (official docs, the tool's own --help, the package's repository); quote each fact with its URL or the command and its output, and say whether it was observed or documented.",
      "Never install, write, or change the machine; a fact that needs an install is unverified, with the command that would show it.",
      "Mark anything unconfirmed unverified, with what was tried; never guess.",
      "Budget: at most 6 WebSearch plus WebFetch calls for your question (research.maxFetches; a hook denies the next one). Try sources in the order the question lists them, and write your findings before the budget runs out, marking anything still unanswered unverified.",
    ],
  };

  const files: AgentFile[] = [
    { path: ".claude/agents/coder.md", content: renderAgent(coder) },
    { path: ".claude/agents/architect.md", content: renderAgent(architect) },
    { path: ".claude/agents/reviewer.md", content: renderAgent(reviewer) },
    { path: ".claude/agents/researcher.md", content: renderAgent(researcher) },
  ];

  if (n.testFramework || d.python.testFramework) {
    const frameworkName = n.testFramework ?? "pytest";
    const tester: AgentSpec = {
      name: "tester",
      description: `Writes and runs tests with ${frameworkName} for a named behavior; edits test files only`,
      readOnly: false,
      facts: buildFacts(d, cfg, { pm: true, singleTest: true }),
      rules: [
        "A new test must fail without the behavior and pass with it.",
        "Edit only test files.",
        "Run each test file you touch with the single-test command.",
        "Report what ran.",
        'When your new tests are meant to stay red until the coder\'s change, end your final message with a JSON object {"tests_red_by_design": ["<test file>", ...]} naming every test file you left failing by its repository-relative path, report the red once, and do not rerun the suite to make a gate pass. Put that JSON line either as the last line of your final plain-text message or inside your hand-back message: the SubagentStop gate reads your last plain-text message first and, when that holds no claim, your last hand-back call.',
        "Scratch files go under `.doug/.state/scratch`; protect-paths keeps refusing the Claude Code session scratchpad, which is outside the project.",
        "Run any command that can take over 120 s, such as pnpm test:unit, with the Bash timeout set to 600000, and hand back only after it exits.",
        "On a tests-only card, run the brief's mutation list yourself in a scratch copy or git worktree under `.doug/.state`, run the one test file there, report each result, and remove the copy; never edit a production file in the live checkout.",
      ],
    };
    files.push({ path: ".claude/agents/tester.md", content: renderAgent(tester) });
  }

  return files;
}
